# Generated by Django 6.0 on 2026-01-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_is_active_remove_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='sole_material',
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='upper_material',
        ),
    ]
