# Generated by Django 6.0 on 2026-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Burgundy', 'Burgundy'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Pink', 'Pink'), ('Multi', 'Multi')], db_index=True, max_length=20, null=True),
        ),
    ]
